### PR TITLE
Fixed docker setup

### PR DESCRIPTION
**Pull request by yunusdemir**
Docker setup is edited and all problems are solved now

### CODE REVIEW

**Comment by lennartkerkvliet** [comment]
@yunusdemir Thanks for adding support for docker-compose. Would you mind adding the new setup to the README?

**Comment by yunusdemir** [comment]
Sure, I'm working on it!

**Comment by yunusdemir** [comment]
README is updated and Docker configurations work completely now. There is a development mode and a production mode.

**Comment by lennartkerkvliet** [comment]
Thanks Yunus, great effort! ✨

**Review by lennartkerkvliet — APPROVED** [review]

**Pull request merged**
